create table if not exists public.user_workspaces (
  user_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.user_workspaces enable row level security;

drop policy if exists "user_workspaces_select_own" on public.user_workspaces;
create policy "user_workspaces_select_own"
on public.user_workspaces
for select
to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "user_workspaces_insert_own" on public.user_workspaces;
create policy "user_workspaces_insert_own"
on public.user_workspaces
for insert
to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "user_workspaces_update_own" on public.user_workspaces;
create policy "user_workspaces_update_own"
on public.user_workspaces
for update
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

create table if not exists public.qa_reports (
  id bigint generated by default as identity primary key,
  author_id text not null,
  text_preview text not null default '',
  issue_count integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists qa_reports_author_id_created_at_idx
  on public.qa_reports (author_id, created_at desc);

alter table public.qa_reports enable row level security;

drop policy if exists "qa_reports_select_own" on public.qa_reports;
create policy "qa_reports_select_own"
on public.qa_reports
for select
to authenticated
using (auth.uid()::text = author_id);

drop policy if exists "qa_reports_insert_own" on public.qa_reports;
create policy "qa_reports_insert_own"
on public.qa_reports
for insert
to authenticated
with check (auth.uid()::text = author_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.stories (
  user_id text not null,
  story_id text not null,
  slug text not null default '',
  title text not null default '',
  content text not null default '',
  introduction text not null default '',
  genre text not null default '',
  type text not null default 'original',
  is_public boolean not null default false,
  is_adult boolean not null default false,
  is_ai boolean not null default false,
  expected_chapters integer not null default 0,
  expected_word_count integer not null default 0,
  story_prompt_notes text not null default '',
  cover_image_url text not null default '',
  translation_memory jsonb not null default '[]'::jsonb,
  character_roster jsonb not null default '[]'::jsonb,
  revision bigint not null default 1,
  sync_hash text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, story_id)
);

create table if not exists public.story_chapters (
  user_id text not null,
  story_id text not null,
  chapter_id text not null,
  title text not null default '',
  content text not null default '',
  sort_order integer not null default 0,
  ai_instructions text not null default '',
  script text not null default '',
  revision bigint not null default 1,
  sync_hash text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, chapter_id)
);

create table if not exists public.workspace_characters (
  user_id text not null,
  character_id text not null,
  story_id text not null default '',
  name text not null default '',
  appearance text not null default '',
  personality text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, character_id)
);

create table if not exists public.workspace_ai_rules (
  user_id text not null,
  rule_id text not null,
  name text not null default '',
  content text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, rule_id)
);

create table if not exists public.workspace_translation_names (
  user_id text not null,
  translation_id text not null,
  original text not null default '',
  translation text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, translation_id)
);

create table if not exists public.workspace_style_references (
  user_id text not null,
  reference_id text not null,
  name text not null default '',
  content text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, reference_id)
);

create table if not exists public.client_error_events (
  id bigint generated by default as identity primary key,
  user_id text null,
  level text not null default 'error',
  source text not null default 'window-error',
  message text not null default '',
  stack text null,
  href text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.api_key_telemetry_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_type text not null default 'request_success',
  provider text not null default '',
  model text not null default '',
  key_fingerprint text not null default '',
  key_hint text not null default '',
  key_id text not null default '',
  task text not null default '',
  success boolean not null default true,
  status_code integer null,
  latency_ms integer not null default 0,
  prompt_chars integer not null default 0,
  response_chars integer not null default 0,
  estimated_tokens integer not null default 0,
  error_message text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists stories_user_id_updated_at_idx on public.stories (user_id, updated_at desc);
create index if not exists story_chapters_user_story_order_idx on public.story_chapters (user_id, story_id, sort_order);
create index if not exists workspace_characters_user_id_idx on public.workspace_characters (user_id);
create index if not exists workspace_ai_rules_user_id_idx on public.workspace_ai_rules (user_id);
create index if not exists workspace_translation_names_user_id_idx on public.workspace_translation_names (user_id);
create index if not exists workspace_style_references_user_id_idx on public.workspace_style_references (user_id);
create index if not exists client_error_events_user_id_created_at_idx on public.client_error_events (user_id, created_at desc);
create index if not exists api_key_telemetry_events_user_id_created_at_idx on public.api_key_telemetry_events (user_id, created_at desc);
create index if not exists api_key_telemetry_events_provider_created_at_idx on public.api_key_telemetry_events (provider, created_at desc);

drop trigger if exists stories_touch_updated_at on public.stories;
create trigger stories_touch_updated_at
before update on public.stories
for each row execute procedure public.touch_updated_at();

drop trigger if exists story_chapters_touch_updated_at on public.story_chapters;
create trigger story_chapters_touch_updated_at
before update on public.story_chapters
for each row execute procedure public.touch_updated_at();

drop trigger if exists workspace_characters_touch_updated_at on public.workspace_characters;
create trigger workspace_characters_touch_updated_at
before update on public.workspace_characters
for each row execute procedure public.touch_updated_at();

drop trigger if exists workspace_ai_rules_touch_updated_at on public.workspace_ai_rules;
create trigger workspace_ai_rules_touch_updated_at
before update on public.workspace_ai_rules
for each row execute procedure public.touch_updated_at();

drop trigger if exists workspace_translation_names_touch_updated_at on public.workspace_translation_names;
create trigger workspace_translation_names_touch_updated_at
before update on public.workspace_translation_names
for each row execute procedure public.touch_updated_at();

drop trigger if exists workspace_style_references_touch_updated_at on public.workspace_style_references;
create trigger workspace_style_references_touch_updated_at
before update on public.workspace_style_references
for each row execute procedure public.touch_updated_at();

alter table public.stories enable row level security;
alter table public.story_chapters enable row level security;
alter table public.workspace_characters enable row level security;
alter table public.workspace_ai_rules enable row level security;
alter table public.workspace_translation_names enable row level security;
alter table public.workspace_style_references enable row level security;
alter table public.client_error_events enable row level security;
alter table public.api_key_telemetry_events enable row level security;

drop policy if exists "stories_select_own" on public.stories;
create policy "stories_select_own" on public.stories
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "stories_insert_own" on public.stories;
create policy "stories_insert_own" on public.stories
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "stories_update_own" on public.stories;
create policy "stories_update_own" on public.stories
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "stories_delete_own" on public.stories;
create policy "stories_delete_own" on public.stories
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "story_chapters_select_own" on public.story_chapters;
create policy "story_chapters_select_own" on public.story_chapters
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "story_chapters_insert_own" on public.story_chapters;
create policy "story_chapters_insert_own" on public.story_chapters
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "story_chapters_update_own" on public.story_chapters;
create policy "story_chapters_update_own" on public.story_chapters
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "story_chapters_delete_own" on public.story_chapters;
create policy "story_chapters_delete_own" on public.story_chapters
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_characters_select_own" on public.workspace_characters;
create policy "workspace_characters_select_own" on public.workspace_characters
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_characters_insert_own" on public.workspace_characters;
create policy "workspace_characters_insert_own" on public.workspace_characters
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_characters_update_own" on public.workspace_characters;
create policy "workspace_characters_update_own" on public.workspace_characters
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_characters_delete_own" on public.workspace_characters;
create policy "workspace_characters_delete_own" on public.workspace_characters
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_ai_rules_select_own" on public.workspace_ai_rules;
create policy "workspace_ai_rules_select_own" on public.workspace_ai_rules
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_ai_rules_insert_own" on public.workspace_ai_rules;
create policy "workspace_ai_rules_insert_own" on public.workspace_ai_rules
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_ai_rules_update_own" on public.workspace_ai_rules;
create policy "workspace_ai_rules_update_own" on public.workspace_ai_rules
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_ai_rules_delete_own" on public.workspace_ai_rules;
create policy "workspace_ai_rules_delete_own" on public.workspace_ai_rules
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_translation_names_select_own" on public.workspace_translation_names;
create policy "workspace_translation_names_select_own" on public.workspace_translation_names
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_translation_names_insert_own" on public.workspace_translation_names;
create policy "workspace_translation_names_insert_own" on public.workspace_translation_names
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_translation_names_update_own" on public.workspace_translation_names;
create policy "workspace_translation_names_update_own" on public.workspace_translation_names
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_translation_names_delete_own" on public.workspace_translation_names;
create policy "workspace_translation_names_delete_own" on public.workspace_translation_names
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_style_references_select_own" on public.workspace_style_references;
create policy "workspace_style_references_select_own" on public.workspace_style_references
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "workspace_style_references_insert_own" on public.workspace_style_references;
create policy "workspace_style_references_insert_own" on public.workspace_style_references
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_style_references_update_own" on public.workspace_style_references;
create policy "workspace_style_references_update_own" on public.workspace_style_references
for update to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "workspace_style_references_delete_own" on public.workspace_style_references;
create policy "workspace_style_references_delete_own" on public.workspace_style_references
for delete to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "client_error_events_insert_any" on public.client_error_events;
drop policy if exists "client_error_events_insert_own" on public.client_error_events;
create policy "client_error_events_insert_own" on public.client_error_events
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "client_error_events_select_own" on public.client_error_events;
create policy "client_error_events_select_own" on public.client_error_events
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "api_key_telemetry_events_insert_own" on public.api_key_telemetry_events;
create policy "api_key_telemetry_events_insert_own" on public.api_key_telemetry_events
for insert to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "api_key_telemetry_events_select_own" on public.api_key_telemetry_events;
create policy "api_key_telemetry_events_select_own" on public.api_key_telemetry_events
for select to authenticated
using (auth.uid()::text = user_id);

drop policy if exists "api_key_telemetry_events_select_admin" on public.api_key_telemetry_events;
create policy "api_key_telemetry_events_select_admin" on public.api_key_telemetry_events
for select to authenticated
using ((auth.jwt() ->> 'email') = 'ductruong.lynx@gmail.com');
